### PR TITLE
CMDCT 3140 PDF Updates

### PR DESCRIPTION
**Pull request by trancjessica**
### Description

This change makes some updates to the PDF. There are still changes to make, but I am putting up the changes I have for now!

Requested Changes 
1. WP PDF: [Submission name table](https://www.figma.com/file/oOJMUZerbafZefLQQ33GwI/MFP_Playground?type=design&node-id=2413%3A99200&mode=design&t=uY5XpHDZusz2Ikio-1): improve alignment for columns to match Figma (the response text should be left-aligned with the table headings), remove the gray rule ✅

Before: 
Screenshot 2023-12-15 at 9 21 10 AM

After: 
Screenshot 2023-12-15 at 9 21 20 AM

------------------------------------------------------

2. WP PDF: [Transition Benchmark Totals Table Heading](https://www.figma.com/file/oOJMUZerbafZefLQQ33GwI/MFP_Playground?type=design&node-id=2413%3A99200&mode=design&t=uY5XpHDZusz2Ikio-1) should be font size XL. 21px (1.25rem) with 130% line-height. It can be designated as an H3 ✅

Before: 
Screenshot 2023-12-15 at 9 25 11 AM

After: 
Screenshot 2023-12-15 at 9 25 24 AM

------------------------------------------------------

3. WP PDF: *asterisk denotes sum of incomplete fields should be body-text-sm .875rem ✅

------------------------------------------------------

4. WP PDF: this report does not have indicator question numbers, [the column with the TH "Indicator" ](https://www.figma.com/file/oOJMUZerbafZefLQQ33GwI/MFP_Playground?type=design&node-id=2413%3A99200&mode=design&t=uY5XpHDZusz2Ikio-1)should have the bold indicator text beneath it (not N/As), and the Responses should be beneath the Response TH ✅

------------------------------------------------------

5. WP PDF: add space between the sections denoted with H2s (64px / 4 rem)
• between Transition Benchmark Totals table and Transition Benchmark Strategy
• between that and State- or Territory-Specific Initiatives Instructions
• between that and State- or Territory-Specific Initiatives
• between each initiative (after the last card if it only has III. Funding sources, or after the table for IV. Close-out information) ✅

6. • Add at least 64px / 4rem space between the end of the content and the top of the MFP footer. ✅

------------------------------------------------------

7. WP PDF: State- or Territory-Specific Initiatives: either remove "See previous page for detailed instructions." and the link because it doesn't work, or change it to be an anchor link upwards to the State- or Territory-Specific Initiatives Instructions heading in the same PDF with the text "See above for detailed instructions." 

------------------------------------------------------

8. WP PDF: double-check styles. Seems ok in the HTML page but huge in the PDF download.

9. Initiative name and Work Plan topic should be specified as H3 and styled to match font size XL. 21px (1.25rem) with 130% line-height. ✅ (this was already done)

10. Headers for I. Define initiative, II. Evaluation plan, III. Funding sources and IV. Close-out information should be H4s — font-size L 18px (1.125rem) with 130% line-height ✅

11. Card headings for the Objective Cards and Funding Source Cards should be specified as H5 and match font-size M 16px (1 rem) with 130% line-height ✅ (this was already done)

12. Card counts in top right corner should be font-size xs (.75rem) and bold (same style as the subheadings for the card, but instead of being color-base like the subheadings, it should be MDCT gray #71767a ✅

------------------------------------------------------

13. [WP PDF Cards](https://www.figma.com/file/oOJMUZerbafZefLQQ33GwI/MFP_Playground?type=design&node-id=2413%3A99200&mode=design&t=uY5XpHDZusz2Ikio-1): Status icons on cards: the corresponding words to the status icons on the cards should be Open sans bold. Looks correct next to each initiative so you can pick up the style from there: class="chakra-text css-1nc5x0f" ✅

------------------------------------------------------

14. WP PDF Cards: instead of the drop-shadow, use a 1px rule around cards rather than the drop shadow, color-gray-light ✅

------------------------------------------------------

### Related ticket(s)

CMDCT-3140
---
### How to test

1. log in as state user
2. you dont necessarily have to fill out a report. Just go to the Review and Submit page :D 
3. Click PDF

### Important updates

---
### Author checklist

- [X] I have performed a self-review of my code
- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Review by keeysnc — DISMISSED** [review]
lgtm!

**Review by britt-mo — APPROVED** [review]

**Review by cassandradanger — DISMISSED** [review]

**Review by gmrabian — CHANGES_REQUESTED** [review]
I don't see the drop shadow on the cards on the home page now!

Screenshot 2023-12-19 at 1 13 11 PM

**Review by gmrabian — DISMISSED** [review]
looks good. Nice work! 😄

**Review by cassandradanger — APPROVED** [review]

**Review by ajaitasaini — APPROVED** [review]
amazing work!!

**Review by cassandradanger — APPROVED** [review]

**Comment by cassandradanger** [comment]
looks so good!! thank you!

**Pull request merged**
