### PR TITLE
WP - Initiatives Details - Close out autosave + autopopulate field

### PR DESCRIPTION
**Pull request by ajaitasaini**
### Description

This ticket will cover three things: 
- auto-populating a disabled field in the close out page
- auto-saving fields
- updating ids to be readable + match with the correct parent

This ticket will NOT cover:
- autosave for nested fields is a known, unresolved bug in MCR and MFP, so that will not work as expected
### Related ticket(s)

MDCT-3026

---
### How to test

- Login
- Go to the Define Initiatives page and fill out the fields, the necessary field to be filled out is the Projected End Date at the bottom. Confirm that autosave is working on this page
- Go to the Close Out page and confirm that the disabled field has autopopulated correctly
- Confirm that fields are autosaving (as of right now, nested fields cannot autosave due to a bug in MCR + MFP)

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Review by cassandradanger — COMMENTED** [review]
Looking good! I'm seeing the auto save, and the disabled due-date populated from define initiative! 
Only thing I'm not seeing save is the text that I entered into the additional text boxes for Discontinued initiative and Sustaining initiative through a Medicaid authority

**Review by gmrabian — APPROVED** [review]
looks good! 
I don't know the state of MFP but I'm assuming saving, page nav buttons, and hydration are all separate

**Comment by ajaitasaini** [comment]
> looks good! I don't know the state of MFP but I'm assuming saving, page nav buttons, and hydration are all separate

thanks for reviewing! there's been a bit of back and forth with how we're going about saving, will add the updates in and then request re-review

**Review by britt-mo — APPROVED** [review]
Worked as expected -- saw autosave occurring & disabled field in IV. Close-out information was populated.

**Review by cassandradanger — APPROVED** [review]

**Pull request merged**
