### PR TITLE
Bufgix SAR PDF page error

### PR DESCRIPTION
**Pull request by keeysnc**
### Description
Fix for SAR Pdf error showing up due to 'createElementWithChildren' not being called. Added a conditional to call createElementWithChildren' when an element has children (ordered or unordered list). 

Error:
screenshot_2024-02-20_at_3 35 24___pm

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Review by britt-mo — APPROVED** [review]
Tested locally, PDF successfully displays

**Review by britt-mo — COMMENTED** [review]
getting this error:
Screenshot 2024-02-23 at 8 12 03 AM

**Review by britt-mo — DISMISSED** [review]
tested again, the PDF loaded correctly

**Review by gmrabian — APPROVED** [review]
no PDF errors after filling out WP and SAR in the UI

**Review by britt-mo — APPROVED** [review]
Checked this out locally, manually entered all data, PDF loaded successfully before filling out the SAR, during, after submission, and resubmission. Didn't see any issues.

**Pull request merged**
