### PR TITLE
[MFP] Global Header/Footer

### PR DESCRIPTION
**Pull request by ajaitasaini**
### Related ticket(s)

MDCT-2329

---
### How to test

- Login
- Confirm that the logo treatment is present for both header and footer

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Comment by ntsummers1** [comment]
Screenshot 2023-08-10 at 4 27 24 PM

The header here is sitting outside of the the vertical middle. This is due to the logo difference. In MCR the logo has a huge empty space inside the image at the bottom. This logo has a much smaller one. I'd eliminate the .5rem margin top of that header image and see how close to a vertical center that gets you.

**Review by karla-vm — DISMISSED** [review]
Seconding what @ntsummers1 said in his previous comment re: the vertical middle, otherwise looks awesome 💯

**Comment by ajaitasaini** [comment]
@ntsummers1 @karla-vm changed the margin to 0.1, removing it completely looked the slightest bit off

**Comment by karla-vm** [comment]
> @ntsummers1 @karla-vm changed the margin to 0.1, removing it completely looked the slightest bit off

just ran locally, this looks great ✨

**Review by karla-vm — APPROVED** [review]

**Review by ntsummers1 — APPROVED** [review]

**Pull request merged**
