### PR TITLE
ui fixes

### PR DESCRIPTION
**Pull request by britt-mo**
### Description
CMDCT-417:
Transition Benchmark Projections

Change text color of bottom text from black to gray. Text to change: "To view Transition Benchmark Totals by target population and by quarter, click Review PDF and it will open a summary in a new tab."

CMDCT-427:
State & Territory Specific Initiatives Instructions

Change text color of "*Required by Program Terms and Conditions" from gray to black
Divider lines for the table may need to be a darker color to match the figma
Divider line required before "Answer the following questions regarding required initiative topics..."
Bottom divider line needs to be a darker color
Confirm that table headers are the right text color/boldness - "Required* Initiatives" and "Optional Initiatives"

CMDCT-470
Currently, the header for this page is "State and Territory-Specific Initiatives Dashboard", should be "State and Territory-Specific Initiatives"

CMDCT-2053
Change header to "State- or Territory-Specific Initiatives: II. Evaluation Plan"
Under instructions, change bolded text color from gray to black
Objective total count text should come before Add objective button 
under add/edit objective modal, add subtext to last field "Provide additional detail on strategies/approaches.."
Add initiative title in Intro on Overlay ModalPage

CMDCT-1916:
Define Initiative page
activities is spelled incorrectly, fix under "Describe the initiative, including key activities:"
Select all that apply. Population you've added as 'Other' in the Transition Benchmarks section will appear here. -> Other should be in double quotes like "Other"
Add other option to target population checklist with the brackets: `Other: {text}`

CMDCT-432
Add initiative modal
Other dropdown should be single line text field, not text area field

---
### How to test
Go to pages listed above in the description, see that the UI matches the requested changes.

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Review by keeysnc — COMMENTED** [review]
`Change text color of "Required by Program Terms and Conditions" from gray to black`

This needs to be updated to black based on the ticket.
Screenshot 2023-11-02 at 12 49 22 PM

**Review by keeysnc — DISMISSED** [review]
Looks good! I found a bug on the 'other' target populations section. It wasn't caused  by any of your code (probably mine lol) but I just realized if you put in the same target population name twice, it treats both of the options as the same one. 

https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/14514294/259e6bfa-529a-426b-859f-7f6dd56a8e78

**Review by ajaitasaini — APPROVED** [review]
chatted on the side about a tiny fix, otherwise looks good!

**Review by ajaitasaini — APPROVED** [review]
looks great!! seeing all the UI fixes

**Pull request merged**
