### PR TITLE
Required Choice Aria Labels for SR 

### PR DESCRIPTION
**Pull request by keeysnc**
### Description
Added aria label descriptions to required WP topics and hint on when adding Initiatives.

WP topics:
Screenshot 2023-12-15 at 3 01 02 PM

Hint:
Screenshot 2023-12-15 at 3 01 40 PM

PDF
Screenshot 2023-12-19 at 11 29 57 AM

Screenshot 2023-12-19 at 11 30 49 AM

### Related ticket(s)
[CMDCT-3130](https://jiraent.cms.gov/browse/CMDCT-3130)

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Review by cassandradanger — COMMENTED** [review]
Should the Self-Direction and Tribal Initiative options in "add Initiative" modal have different aria labels, since they're only required "if applicable" ?
Screenshot 2023-12-18 at 2 47 46 PM

**Review by cassandradanger — COMMENTED** [review]
in the Jira tkt, it says something about the PDF - were any updates needed for the PDF?

**Comment by keeysnc** [comment]
Reviewed and approved by Kim

**Review by gmrabian — DISMISSED** [review]
tested with VoiceOver and everything checked out

**Review by gmrabian — APPROVED** [review]

**Pull request merged**
