### PR TITLE
[3420, 3418] Fixing more console errors

### PR DESCRIPTION
**Pull request by jessabean**
### Description
Fixing more console errors in the unit tests

### Related ticket(s)

CMDCT-3420
CMDCT-3418

---
### How to test

Run the following test suites, notice no more console errors:

- ModalDrawerReportPage
- ModalOverlayReportPage
- ChoiceListField
- DateField
- NumberField
- TextField

### CODE REVIEW

**Review by gmrabian — DISMISSED** [review]
I think there may have been some properties in here for text areas that is now gone. Text area form fields shrunk

Screenshot 2024-05-07 at 4 31 47 PM
Screenshot 2024-05-07 at 4 32 26 PM

**Comment by jessabean** [comment]
@gmrabian I pushed up a fix for this. Thanks for the 🦅 👁️ !

**Review by benmartin-coforma — APPROVED** [review]
Looks good to me! The `data-testid="text-test-field"` attribute on the test components in TextField.test.tsx are unused now, so you could clear those out if you liked. But I approve regardless; this is a good change.

**Review by karla-vm — APPROVED** [review]

**Review by ntsummers1 — APPROVED** [review]

**Comment by gmrabian** [comment]
https://d14gao2x4phptl.cloudfront.net/
Ok I don't know what is wrong but I can't see the buttons on the homepage (are they turned off in Launch Darkly?)
Screenshot 2024-05-10 at 9 30 11 AM

**Review by gmrabian — APPROVED** [review]

**Review by BearHanded — APPROVED** [review]

**Pull request merged**
