### PR TITLE
[MFP] WP - Initiatives Details - Close out functionality

### PR DESCRIPTION
**Pull request by ajaitasaini**
### Related ticket(s)

MDCT-2998

### What this PR covers
- Initiative does in fact, close out and that information is saved and sent to the db (the only changes that are visible right now would show up in the network tab) 

### What this PR does not cover/yet to be worked on
- autosave & hydration :) [CMDCT-194](https://jiraent.cms.gov/browse/CMDCT-194)
- disabled close out button + return to dashboard button [CMDCT-201](https://jiraent.cms.gov/browse/CMDCT-201)
- Pressing "Yes, close out initiative" or "Save and return" takes user back to the initiative dashboard [CMDCT-204](https://jiraent.cms.gov/browse/CMDCT-204)

### What I'd like feedback on
- Am I sending the correct data to the db? Did I implement this correctly (is there any risk of my code overwriting data that it's not supposed to)? Is there anything I'm missing that would be helpful for statusing/accessing initiatives in SAR?

---
### How to test

- Confirm that on closing out the initiative, correct fieldData + isInitiativeClosed=true is submitted to the db
- Confirm that on Save & Return, correct fieldData is submitted to the db
- Confirm that fieldData is nested per initiative (create multiple initiatives, make sure that each initiative has correct field data)

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Review by gmrabian — APPROVED** [review]
Tested locally and it looks like it's working as expected!

Initiatives save at the correct level.
Closing initiatives adds the associated boolean.
Creating/editing initiatives when there are multiple does not overwrite others.

**Review by ailZhou — COMMENTED** [review]
:( it's not working on the deploy site, won't save or close out. i really hope it's just me.

**Comment by ajaitasaini** [comment]
> :( it's not working on the deploy site, won't save or close out. i really hope it's just me.

@ailZhou do you mind logging in with stateuser2? i noticed that for some logins it won't absorb the PR's changes, i tested it out with that login and it seemed to work

**Comment by britt-mo** [comment]
> > :( it's not working on the deploy site, won't save or close out. i really hope it's just me.
> 
> @ailZhou do you mind logging in with stateuser2? i noticed that for some logins it won't absorb the PR's changes, i tested it out with that login and it seemed to work

I had the same experience as Aileen, tried `stateuser` and `stateuser2`.

**Comment by trancjessica** [comment]
> > > :( it's not working on the deploy site, won't save or close out. i really hope it's just me.
> > 
> > 
> > @ailZhou do you mind logging in with stateuser2? i noticed that for some logins it won't absorb the PR's changes, i tested it out with that login and it seemed to work
> 
> I had the same experience as Aileen, tried `stateuser` and `stateuser2`.

I had the same experience as Aileen and Britt - "Close out initiative" doesn't save or close out for `stateuser2` or `stateuser` . (Perhaps related - I also noticed `Define Initiative`'s Save and Return doesn't save or return) :(

**Review by cassandradanger — APPROVED** [review]
I am seeing that the `isInitiativeClosed`, but the other initiatives don't have that key - I would expect the other initiatives to have `isInitiativeClosed` set to false. I wonder if we should update the Create Initiative post to include the `isInitiativeClosed` key.
That could be done in a separate tkt though

**Comment by ajaitasaini** [comment]
> I am seeing that the `isInitiativeClosed` is set to true, but the other initiatives don't have that key - I would expect the other initiatives to have `isInitiativeClosed` set to false. I wonder if we should update the Create Initiative post to include the `isInitiativeClosed` key. That could be done in a separate tkt though

resolved offline, the request by devs was to only have `isInitiativeClosed=true` exist in the database, otherwise not exist as a flag, to minimize where this shows up in the db - aka we'll never see `isInitiativeClosed=false`

**Pull request merged**
